---
title: 'LRT: t-test vs chi-square'
author: '[F. Javier Rubio](https://sites.google.com/site/fjavierrubio67/)'
date: "10/03/2019"
output: html_document
---

# t-test $n=100$

```{r }
rm(list=ls())
# Required packages
library(sn)
library(knitr)

indicator = vector()
n <- 100
mu0 <- 0

for(i in 1:10000){
  # Simulated data
  set.seed(i)
  data.sim <- rnorm(n,0,1)
  
  # Test statistic
  Tn <- abs(mean(data.sim) - mu0)/sqrt(var(data.sim)/n)
  
  # 0.975 Quantile of a t distribution with n-1 d.f.
  q <- qt(0.975, df = n-1)
  
  # Outcome from the test
  indicator[i] <- ifelse(Tn > q, 1, 0)
}

# Approximate size
mean(indicator)

```



# t-test $n=1000$

```{r }
rm(list=ls())
# Required packages
library(sn)
library(knitr)

indicator = vector()
n <- 1000
mu0 <- 0

for(i in 1:10000){
  # Simulated data
  set.seed(i)
  data.sim <- rnorm(n,0,1)
  
  # Test statistic
  Tn <- abs(mean(data.sim) - mu0)/sqrt(var(data.sim)/n)
  
  # 0.975 Quantile of a t distribution with n-1 d.f.
  q <- qt(0.975, df = n-1)
  
  # Outcome from the test
  indicator[i] <- ifelse(Tn > q, 1, 0)
}

# Approximate size
mean(indicator)

```


# $\chi^2$ approximation $n=100$

```{r }
rm(list=ls())
# Required packages
library(sn)
library(knitr)

indicator = vector()
n <- 100
mu0 <- 0

for(i in 1:10000){
  # Simulated data
  set.seed(i)
  data.sim <- rnorm(n,0,1)
  
  # LRT Test statistic
  barx = mean(data.sim)
  LRT <- -n*log( 1/( 1 + n*(barx-mu0)^2/sum((data.sim-barx)^2) ))
  
  # 0.95 Quantile of a t distribution with n-1 d.f.
  q <- qchisq(0.95, df = 1)
  
  # Outcome from the test
  indicator[i] <- ifelse(LRT > q, 1, 0)
}

# Approximate size
mean(indicator)

```


# $\chi^2$ approximation $n=1000$

```{r }
rm(list=ls())
# Required packages
library(sn)
library(knitr)

indicator = vector()
n <- 1000
mu0 <- 0

for(i in 1:10000){
  # Simulated data
  set.seed(i)
  data.sim <- rnorm(n,0,1)
  
  # LRT Test statistic
  barx = mean(data.sim)
  LRT <- -n*log( 1/( 1 + n*(barx-mu0)^2/sum((data.sim-barx)^2) ))
  
  # 0.95 Quantile of a t distribution with n-1 d.f.
  q <- qchisq(0.95, df = 1)
  
  # Outcome from the test
  indicator[i] <- ifelse(LRT > q, 1, 0)
}

# Approximate size
mean(indicator)

```